// components/CategoryData.js
export const CategoryData = {
  categories: ["Mobile", "Laptop", "Sports", "Others"],
  subcategories: {
    Mobile: [
      "Mobile Accessories",
      "Mobile Sim Card",
      "Mobile Display",
      "earphone",
      "charger",
    ],
    Sports: ["badminton", "cricket bat", "Football gloves"],
    Laptop: ["Laptop Accessories", "Laptop Bags", "Laptop Charger"],
    Others: ["Electronics", "Clothing", "Books", "watch"],
  },
  division: [
    "Dhaka",
    "Khulna",
    "Rajshahi",
    "Chattragram",
    "Rangpur",
    "Mymensing",
    "Sylet",
  ],
  distric: {
    Dhaka: ["Kishorgonj", "Gazipur", "Mirpur"],
    Khulna: ["Magura"],
    Rajshahi: ["Natore", "ChapaiNobabgonj"],
    Chattragram: ["Cox-Bazar", "Sitakunda"],
    Mymensing: ["Sherpur", "Jamalpur"],
    Sylet: ["Shrimongol"],
    Rangpur: ["Rangpur sadar"],
  },
  optionsArray: [
    { value: "realme" },
    { value: "vivo" },
    { value: "asus" },
    { value: "samsung" },
    { value: "walton" },
    { value: "sony" },
    { value: "nokia" },
    { value: "kiam" },
    { value: "xaomi" },
    { value: "hp" },
    { value: "dell" },
    { value: "others" },
  ],
};
